    destination: ./_site
    lsi:         false
    port:        4000
    pygments:    true
    permalink:   date
    name: Sean Anderson
    description: Web log by Sean Anderson
    url: http://seananderson.ca
    safe: true
    markdown: redcarpet
    redcarpet:
      extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
